version: '3.10'
networks:
  demo_app_huyen:
    driver: bridge
services:
  db:
    image: postgres:14.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gzr2efGPYs
      POSTGRES_DB: demodb
    ports:
      - 5433:5432
    networks:
      - demo_app_huyen
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:gzr2efGPYs@db:5432/demodb
    depends_on:
    - db
    networks:
      - demo_app_huyen